// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`

/// Download and checksum-verify one model, or every required model when `model` is `None`.
///
/// # Errors
///
/// Returns an error if a download, write, or checksum verification fails.
Future<List<String>> install({MixupModel? model, required String path}) =>
    MixupRustLib.instance.api.crateApiInstall(model: model, path: path);

/// Analyze tempo, four-beat bars, and per-bar vocal activity in `input`.
///
/// # Errors
///
/// Returns an error when models cannot be loaded or the audio cannot be decoded and analyzed.
Future<TrackAnalysis> analyze({
  required String input,
  required String models,
}) => MixupRustLib.instance.api.crateApiAnalyze(input: input, models: models);

/// Analysis values for one four-beat musical bar.
class BarAnalysis {
  final BigInt number;
  final double startSeconds;
  final double endSeconds;
  final Float32List beatsSeconds;
  final double beatConfidence;
  final double vocalProbability;
  final double acousticVocalProbability;
  final VocalState vocalState;

  const BarAnalysis({
    required this.number,
    required this.startSeconds,
    required this.endSeconds,
    required this.beatsSeconds,
    required this.beatConfidence,
    required this.vocalProbability,
    required this.acousticVocalProbability,
    required this.vocalState,
  });

  @override
  int get hashCode =>
      number.hashCode ^
      startSeconds.hashCode ^
      endSeconds.hashCode ^
      beatsSeconds.hashCode ^
      beatConfidence.hashCode ^
      vocalProbability.hashCode ^
      acousticVocalProbability.hashCode ^
      vocalState.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BarAnalysis &&
          runtimeType == other.runtimeType &&
          number == other.number &&
          startSeconds == other.startSeconds &&
          endSeconds == other.endSeconds &&
          beatsSeconds == other.beatsSeconds &&
          beatConfidence == other.beatConfidence &&
          vocalProbability == other.vocalProbability &&
          acousticVocalProbability == other.acousticVocalProbability &&
          vocalState == other.vocalState;
}

/// Analyzer model that can be installed independently.
enum MixupModel {
  /// Mel-spectrogram preprocessing model.
  melSpectrogram,

  /// Small Beat This beat-tracking model.
  beatThisSmall,
}

/// Complete analysis returned by the Mixup engine.
class TrackAnalysis {
  final String analyzerVersion;
  final double tempoBpm;
  final List<BarAnalysis> bars;
  final double beatConfidence;
  final List<String> warnings;

  const TrackAnalysis({
    required this.analyzerVersion,
    required this.tempoBpm,
    required this.bars,
    required this.beatConfidence,
    required this.warnings,
  });

  @override
  int get hashCode =>
      analyzerVersion.hashCode ^
      tempoBpm.hashCode ^
      bars.hashCode ^
      beatConfidence.hashCode ^
      warnings.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TrackAnalysis &&
          runtimeType == other.runtimeType &&
          analyzerVersion == other.analyzerVersion &&
          tempoBpm == other.tempoBpm &&
          bars == other.bars &&
          beatConfidence == other.beatConfidence &&
          warnings == other.warnings;
}

/// Coarse vocal classification for a four-beat bar.
enum VocalState { vocal, instrumental, uncertain }
