// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class MixupRustLib
    extends
        BaseEntrypoint<MixupRustLibApi, MixupRustLibApiImpl, MixupRustLibWire> {
  @internal
  static final instance = MixupRustLib._();

  MixupRustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    MixupRustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required MixupRustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<MixupRustLibApiImpl, MixupRustLibWire>
  get apiImplConstructor => MixupRustLibApiImpl.new;

  @override
  WireConstructor<MixupRustLibWire> get wireConstructor =>
      MixupRustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 770580912;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'mixup_ffi',
        ioDirectory: '../../engine/crates/bridge/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class MixupRustLibApi extends BaseApi {
  Future<TrackAnalysis> crateApiAnalyze({
    required String input,
    required String models,
  });

  Future<List<String>> crateApiInstall({
    MixupModel? model,
    required String path,
  });
}

class MixupRustLibApiImpl extends MixupRustLibApiImplPlatform
    implements MixupRustLibApi {
  MixupRustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<TrackAnalysis> crateApiAnalyze({
    required String input,
    required String models,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(input, serializer);
          sse_encode_String(models, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_track_analysis,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiAnalyzeConstMeta,
        argValues: [input, models],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAnalyzeConstMeta =>
      const TaskConstMeta(debugName: "analyze", argNames: ["input", "models"]);

  @override
  Future<List<String>> crateApiInstall({
    MixupModel? model,
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_box_autoadd_mixup_model(model, serializer);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiInstallConstMeta,
        argValues: [model, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInstallConstMeta =>
      const TaskConstMeta(debugName: "install", argNames: ["model", "path"]);

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  BarAnalysis dco_decode_bar_analysis(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return BarAnalysis(
      number: dco_decode_usize(arr[0]),
      startSeconds: dco_decode_f_32(arr[1]),
      endSeconds: dco_decode_f_32(arr[2]),
      beatsSeconds: dco_decode_list_prim_f_32_strict(arr[3]),
      beatConfidence: dco_decode_f_32(arr[4]),
      vocalProbability: dco_decode_f_32(arr[5]),
      acousticVocalProbability: dco_decode_f_32(arr[6]),
      vocalState: dco_decode_vocal_state(arr[7]),
    );
  }

  @protected
  MixupModel dco_decode_box_autoadd_mixup_model(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_mixup_model(raw);
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<BarAnalysis> dco_decode_list_bar_analysis(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_bar_analysis).toList();
  }

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Float32List;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  MixupModel dco_decode_mixup_model(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MixupModel.values[raw as int];
  }

  @protected
  MixupModel? dco_decode_opt_box_autoadd_mixup_model(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_mixup_model(raw);
  }

  @protected
  TrackAnalysis dco_decode_track_analysis(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return TrackAnalysis(
      analyzerVersion: dco_decode_String(arr[0]),
      tempoBpm: dco_decode_f_32(arr[1]),
      bars: dco_decode_list_bar_analysis(arr[2]),
      beatConfidence: dco_decode_f_32(arr[3]),
      warnings: dco_decode_list_String(arr[4]),
    );
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  VocalState dco_decode_vocal_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return VocalState.values[raw as int];
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  BarAnalysis sse_decode_bar_analysis(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_number = sse_decode_usize(deserializer);
    var var_startSeconds = sse_decode_f_32(deserializer);
    var var_endSeconds = sse_decode_f_32(deserializer);
    var var_beatsSeconds = sse_decode_list_prim_f_32_strict(deserializer);
    var var_beatConfidence = sse_decode_f_32(deserializer);
    var var_vocalProbability = sse_decode_f_32(deserializer);
    var var_acousticVocalProbability = sse_decode_f_32(deserializer);
    var var_vocalState = sse_decode_vocal_state(deserializer);
    return BarAnalysis(
      number: var_number,
      startSeconds: var_startSeconds,
      endSeconds: var_endSeconds,
      beatsSeconds: var_beatsSeconds,
      beatConfidence: var_beatConfidence,
      vocalProbability: var_vocalProbability,
      acousticVocalProbability: var_acousticVocalProbability,
      vocalState: var_vocalState,
    );
  }

  @protected
  MixupModel sse_decode_box_autoadd_mixup_model(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_mixup_model(deserializer));
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<BarAnalysis> sse_decode_list_bar_analysis(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <BarAnalysis>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_bar_analysis(deserializer));
    }
    return ans_;
  }

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getFloat32List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  MixupModel sse_decode_mixup_model(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return MixupModel.values[inner];
  }

  @protected
  MixupModel? sse_decode_opt_box_autoadd_mixup_model(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_mixup_model(deserializer));
    } else {
      return null;
    }
  }

  @protected
  TrackAnalysis sse_decode_track_analysis(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_analyzerVersion = sse_decode_String(deserializer);
    var var_tempoBpm = sse_decode_f_32(deserializer);
    var var_bars = sse_decode_list_bar_analysis(deserializer);
    var var_beatConfidence = sse_decode_f_32(deserializer);
    var var_warnings = sse_decode_list_String(deserializer);
    return TrackAnalysis(
      analyzerVersion: var_analyzerVersion,
      tempoBpm: var_tempoBpm,
      bars: var_bars,
      beatConfidence: var_beatConfidence,
      warnings: var_warnings,
    );
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  VocalState sse_decode_vocal_state(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return VocalState.values[inner];
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bar_analysis(BarAnalysis self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(self.number, serializer);
    sse_encode_f_32(self.startSeconds, serializer);
    sse_encode_f_32(self.endSeconds, serializer);
    sse_encode_list_prim_f_32_strict(self.beatsSeconds, serializer);
    sse_encode_f_32(self.beatConfidence, serializer);
    sse_encode_f_32(self.vocalProbability, serializer);
    sse_encode_f_32(self.acousticVocalProbability, serializer);
    sse_encode_vocal_state(self.vocalState, serializer);
  }

  @protected
  void sse_encode_box_autoadd_mixup_model(
    MixupModel self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_mixup_model(self, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_bar_analysis(
    List<BarAnalysis> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_bar_analysis(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_f_32_strict(
    Float32List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putFloat32List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_mixup_model(MixupModel self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_opt_box_autoadd_mixup_model(
    MixupModel? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_mixup_model(self, serializer);
    }
  }

  @protected
  void sse_encode_track_analysis(TrackAnalysis self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.analyzerVersion, serializer);
    sse_encode_f_32(self.tempoBpm, serializer);
    sse_encode_list_bar_analysis(self.bars, serializer);
    sse_encode_f_32(self.beatConfidence, serializer);
    sse_encode_list_String(self.warnings, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_vocal_state(VocalState self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }
}
